version: '2.4'

services:
  collect-left: &collect-left
    command:
      - emporia-vue-logger-collect-records
      - --flagfile=data/collect-left-flags.txt
    image: emporia-vue-logger
    init: true
    mem_limit: 128M
    restart: unless-stopped
    volumes:
      - data:/app/data

  collect-right:
    <<: *collect-left
    command:
      - emporia-vue-logger-collect-records
      - --flagfile=data/collect-right-flags.txt

  write-prod:
    <<: *collect-left
    command:
      - line-protocol-cache-consumer
      - --flagfile=data/write-prod-flags.txt

volumes:
  data:
